# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: shipyard
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
-
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - GPG_TTY=$(tty)

  binary: shipyard

  ldflags:
    - -s -w -X main.version={{.Version}} -X main.date={{.CommitDate}} -X main.commit={{.Commit}}

  goos:
    - linux
    - darwin
    - windows

  goarch:
    - amd64
    - arm
    - arm64

  goarm:
    - 7
    - 6

  ignore:
    - goos: windows
      goarch: arm
      goarm: 7
    - goos: windows
      goarch: arm
      goarm: 6

nfpms:
  -
    package_name: shipyard
    vendor: Shipyard Inc
    homepage: https://shipyard.run
    maintainer: Nic Jackson and Erik Veld <mail@shipyard.run>
    license: Mozilla Public License, version 2.0
    formats:
      - deb
      - rpm

snapcrafts:
  -
    name: shipyard

archives:
- replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
  - goos: darwin
    format: zip
snapshot:
  name_template: "{{ .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

release:
  disable:  true