---

name: Build
on: [push]
jobs:
  build:
    env:
      GONOSUMDB: "github.com/moby/moby"
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup Go version
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14.4'  # The Go version to download (if necessary) and use.

      - name: Get dependencies
        run: |
          go version
          go get -v -t ./...

      - name: Unit Test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic -short ./...

      - name: Build
        run: |
          go build -v .

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # required

  functional_test:
    name: Functional Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [
          './examples/container',
          './examples/build',
          './examples/docs',
          './examples/modules',
          './examples/single_k3s_cluster',
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go version
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14.4'  # The Go version to download (if necessary) and use.

      - name: Run tests
        run: |
          go run main.go purge
          go run main.go test ${matrix.folder}

      - name: E2E test for build binary
        run: make test_e2e_cmd

  e2e_linux:
    name: Functional Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go version
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14.4'  # The Go version to download (if necessary) and use.

      - name: E2E test for build binary
        run: make test_e2e_cmd

  e2e_windows:
    name: Windows E2E tests
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go version
        uses: actions/setup-go@v2-beta
        with:
          go-version: '1.14.4'  # The Go version to download (if necessary) and use.

      - name: Build a windows binary
        run: go build -ldflags "-X main.version=e2e" -o bin/yard-windows.exe main.go

      - name: E2E test for build binary
        run: |
          bin\yard-windows.exe run --no-browser github.com/shipyard-run/blueprints//consul-terminating-gateways
          bin\yard-windows.exe destroy
