---

name: Build
on: [push]
jobs:
  build:
    env:
      GONOSUMDB: "github.com/moby/moby"
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup Go version
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.2

      - name: Get dependencies
        run: |
          go version
          go get -v -t ./...

      - name: Unit Test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic -short ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.147.2
          args: release --rm-dist --snapshot
          key: ${{ secrets.GPG_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: shipyard
          path: |
            dist/shipyard_darwin_amd64
            dist/shipyard_linux_amd64
            dist/shipyard_linux_arm64
            dist/shipyard_linux_arm_7
            dist/shipyard_linux_arm_6
            dist/shipyard_windows_amd64

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # required

      - name: Send status to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  functional_test:
    name: Functional Test
    runs-on: ubuntu-latest
    needs: build

    strategy:
      matrix:
        folder: [
          './examples/container',
          './examples/build',
          './examples/docs',
          './examples/modules',
          './examples/single_k3s_cluster',
          './examples/nomad',
        ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go version
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.2

      - name: Run tests
        run: |
          go run main.go purge
          go run main.go test ${{matrix.folder}}

      - name: Send status to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  e2e_linux:
    name: Linux E2E Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Setup Go version
        uses: actions/setup-go@v1
        with:
          go-version: 1.15.2

      - name: E2E test for build binary
        run: make test_e2e_cmd

      - name: Send status to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  e2e_mac:
    name: Mac E2E Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: '${{ secrets.GH_TOKEN }}'
          repository: shipyard-run/shipyard-mac-build
          event-type: test
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'

      - name: Send status to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}

  tag:
    name: Tag latest release
    runs-on: ubuntu-latest
    needs:
      - build
      - functional_test
      - e2e_mac
      - e2e_linux
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Send status to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: "Automatically tagged main branch with new tag: ${{ steps.tag_version.outputs.new_tag }}"

    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}


  push_docker:
    name: Push Docker container to Docker Hub
    runs-on: ubuntu-latest
    needs: tag
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Push image
        run: docker push shipyardrun/shipyard:${{ needs.tag.outputs.outputs.new_tag }}

      - name: Send status to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          tile: ${{ github.job_id }}
          description: "Push image shipyardrun/shipyard:${{ needs.tag.outputs.outputs.new_tag }} to DockerHub"

  choco:
    runs-on: windows-latest
    needs: tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'shipyard-run/choco'

      - name: Install dependencies
        run: |
          choco install checksum -y
          choco install wget -y

      - name: Tag
        id: tag
        uses: ashley-taylor/regex-property-action@v1.0
        with:
          value: ${{ needs.tag.outputs.outputs.new_tag }}
          regex: "v"
          replacement: ""

      - name: Replace checksum
        run: |
          wget "https://github.com/shipyard-run/shipyard/releases/download/v${{ steps.tag.outputs.value }}/shipyard_${{ steps.tag.outputs.value }}_Windows_x86_64.zip"
          powershell -Command "(gc tools/chocolateyinstall.ps1) -replace '__checksum__', '$(checksum -t sha256 -f shipyard_${{ steps.tag.outputs.value }}_Windows_x86_64.zip)' | Out-File -encoding ASCII tools/chocolateyinstall.ps1"

      - name: Replace version
        run: |
          powershell -Command "(gc shipyard.nuspec) -replace '__version__', '${{ steps.tag.outputs.value }}' | Out-File -encoding ASCII shipyard.nuspec"
          powershell -Command "(gc tools/chocolateyinstall.ps1) -replace '__version__', '${{ steps.tag.outputs.value }}' | Out-File -encoding ASCII tools\chocolateyinstall.ps1"

      - name: Choco login
        run: choco apikey -k ${{ secrets.CHOCO_API_KEY }} -s https://push.chocolatey.org/

      - name: Choco build
        run: choco pack

      - name: Choco push
        run: choco push -f

      - name: Send status to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          tile: ${{ github.job_id }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: "Push new version ${{ needs.tag.outputs.outputs.new_tag }} to Chocolatey"

  apt:
    needs: tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["amd64.deb", "arm64.deb", "armv7.deb", "amd64.rpm", "arm64.rpm", "armv7.rpm"]

    steps:
    - name: Tag
      id: tag
      uses: ashley-taylor/regex-property-action@v1.0
      with:
        value: ${{ needs.tag.outputs.outputs.new_tag }}
        regex: "v"
        replacement: ""

    - name: Download release
      run: |
        wget "https://github.com/shipyard-run/shipyard/releases/download/v${{ steps.tag.outputs.value }}/shipyard_${{ steps.tag.outputs.value }}_linux_${{ matrix.arch }}"

    - name: Upload release
      run: |
        curl -F package=@shipyard_${{ steps.tag.outputs.value }}_linux_${{ matrix.arch }} https://${{ secrets.FURY_TOKEN }}@push.fury.io/shipyard-run/

    - name: Send status to Discord
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        tile: ${{ github.job_id }}
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        description: "Push new version ${{ needs.tag.outputs.outputs.new_tag }} to Apt"

  update_website:
    needs: tag
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 'shipyard-run/shipyard-website'
          token: '${{ secrets.GH_TOKEN }}'

      - name: Configure Git
        run: |
          git config user.email "mail@shipyard.run"
          git config user.name "Shipyard Bot"

      - name: Tag
        id: tag
        uses: ashley-taylor/regex-property-action@v1.0
        with:
          value: ${{ github.ref }}
          regex: "refs/tags/v"
          replacement: ""

      - name: Write version
        run: |
          echo "${{ steps.tag.outputs.value }}" > ./static/latest

      - name: Push update
        run: |

          git add .
          git commit -m "Update version to ${{ steps.tag.outputs.value}}"
          git push

      - name: Send status to Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          tile: ${{ github.job_id }}
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          description: "Update website with latest version ${{ needs.tag.outputs.outputs.new_tag }}"
